name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  merge-me:
    name: Merge me!
    needs:
      - all
      - other
      - required
      - jobs
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
