# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  merge-me:
    name: Merge me!
    uses: ridedott/merge-me-action@v1.1.8
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
